{% set name = "azure-mgmt-sqlvirtualmachine" %}
{% set version = "1.0.0b5" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: 6458097e58329d14b1a3e07e56ca38797d4985e5a50d08df27d426ba95f2a4c7

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<37]

requirements:
  host:
    - setuptools
    - wheel
    - python
    - pip
  run:
    - python
    - msrest >=0.7.1
    - azure-common >=1.1,<2
    - azure-mgmt-core >=1.3.2,<2.0.0
    - typing-extensions >=4.3.0  # [py<38]

test:
  imports:
    - azure.mgmt.sqlvirtualmachine
    - azure.mgmt.sqlvirtualmachine.models
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Azure/azure-sdk-for-python
  summary: Microsoft Azure SQL Virtual Machine Management Client Library for Python
  license: MIT
  license_file: LICENSE
  license_family: MIT
  description: Microsoft Azure SQL Virtual Machine Management Client Library for Python
  dev_url: https://github.com/Azure/azure-sdk-for-python
  doc_url: https://github.com/Azure/azure-sdk-for-python

extra:
  recipe-maintainers:
    - janjagusch
